// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from "@tanstack/react-query";
import type { AxiosError } from "axios";

import { client } from "../client.gen";
import {
  deleteApiV1ActivitiesById,
  deleteApiV1AuthorsById,
  deleteApiV1BooksById,
  deleteApiV1UsersById,
  getApiV1Activities,
  getApiV1ActivitiesById,
  getApiV1Authors,
  getApiV1AuthorsAuthorsBooksByIdBook,
  getApiV1AuthorsById,
  getApiV1Books,
  getApiV1BooksById,
  getApiV1Users,
  getApiV1UsersById,
  type Options,
  postApiV1Activities,
  postApiV1Authors,
  postApiV1Books,
  postApiV1Users,
  putApiV1ActivitiesById,
  putApiV1AuthorsById,
  putApiV1BooksById,
  putApiV1UsersById,
} from "../sdk.gen";
import type {
  DeleteApiV1ActivitiesByIdData,
  DeleteApiV1AuthorsByIdData,
  DeleteApiV1BooksByIdData,
  DeleteApiV1UsersByIdData,
  GetApiV1ActivitiesByIdData,
  GetApiV1ActivitiesByIdResponse,
  GetApiV1ActivitiesData,
  GetApiV1ActivitiesResponse,
  GetApiV1AuthorsAuthorsBooksByIdBookData,
  GetApiV1AuthorsAuthorsBooksByIdBookResponse,
  GetApiV1AuthorsByIdData,
  GetApiV1AuthorsByIdResponse,
  GetApiV1AuthorsData,
  GetApiV1AuthorsResponse,
  GetApiV1BooksByIdData,
  GetApiV1BooksByIdResponse,
  GetApiV1BooksData,
  GetApiV1BooksResponse,
  GetApiV1UsersByIdData,
  GetApiV1UsersData,
  GetApiV1UsersResponse,
  PostApiV1ActivitiesData,
  PostApiV1ActivitiesResponse,
  PostApiV1AuthorsData,
  PostApiV1AuthorsResponse,
  PostApiV1BooksData,
  PostApiV1UsersData,
  PutApiV1ActivitiesByIdData,
  PutApiV1ActivitiesByIdResponse,
  PutApiV1AuthorsByIdData,
  PutApiV1AuthorsByIdResponse,
  PutApiV1BooksByIdData,
  PutApiV1UsersByIdData,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiV1ActivitiesQueryKey = (options?: Options<GetApiV1ActivitiesData>) =>
  createQueryKey("getApiV1Activities", options);

export const getApiV1ActivitiesOptions = (options?: Options<GetApiV1ActivitiesData>) =>
  queryOptions<
    GetApiV1ActivitiesResponse,
    AxiosError<DefaultError>,
    GetApiV1ActivitiesResponse,
    ReturnType<typeof getApiV1ActivitiesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1Activities({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1ActivitiesQueryKey(options),
  });

export const postApiV1ActivitiesMutation = (
  options?: Partial<Options<PostApiV1ActivitiesData>>,
): UseMutationOptions<PostApiV1ActivitiesResponse, AxiosError<DefaultError>, Options<PostApiV1ActivitiesData>> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1ActivitiesResponse,
    AxiosError<DefaultError>,
    Options<PostApiV1ActivitiesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1Activities({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteApiV1ActivitiesByIdMutation = (
  options?: Partial<Options<DeleteApiV1ActivitiesByIdData>>,
): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiV1ActivitiesByIdData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<DeleteApiV1ActivitiesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiV1ActivitiesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1ActivitiesByIdQueryKey = (options: Options<GetApiV1ActivitiesByIdData>) =>
  createQueryKey("getApiV1ActivitiesById", options);

export const getApiV1ActivitiesByIdOptions = (options: Options<GetApiV1ActivitiesByIdData>) =>
  queryOptions<
    GetApiV1ActivitiesByIdResponse,
    AxiosError<DefaultError>,
    GetApiV1ActivitiesByIdResponse,
    ReturnType<typeof getApiV1ActivitiesByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1ActivitiesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1ActivitiesByIdQueryKey(options),
  });

export const putApiV1ActivitiesByIdMutation = (
  options?: Partial<Options<PutApiV1ActivitiesByIdData>>,
): UseMutationOptions<
  PutApiV1ActivitiesByIdResponse,
  AxiosError<DefaultError>,
  Options<PutApiV1ActivitiesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiV1ActivitiesByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiV1ActivitiesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiV1ActivitiesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1AuthorsQueryKey = (options?: Options<GetApiV1AuthorsData>) =>
  createQueryKey("getApiV1Authors", options);

export const getApiV1AuthorsOptions = (options?: Options<GetApiV1AuthorsData>) =>
  queryOptions<
    GetApiV1AuthorsResponse,
    AxiosError<DefaultError>,
    GetApiV1AuthorsResponse,
    ReturnType<typeof getApiV1AuthorsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1Authors({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthorsQueryKey(options),
  });

export const postApiV1AuthorsMutation = (
  options?: Partial<Options<PostApiV1AuthorsData>>,
): UseMutationOptions<PostApiV1AuthorsResponse, AxiosError<DefaultError>, Options<PostApiV1AuthorsData>> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthorsResponse,
    AxiosError<DefaultError>,
    Options<PostApiV1AuthorsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1Authors({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1AuthorsAuthorsBooksByIdBookQueryKey = (
  options: Options<GetApiV1AuthorsAuthorsBooksByIdBookData>,
) => createQueryKey("getApiV1AuthorsAuthorsBooksByIdBook", options);

export const getApiV1AuthorsAuthorsBooksByIdBookOptions = (options: Options<GetApiV1AuthorsAuthorsBooksByIdBookData>) =>
  queryOptions<
    GetApiV1AuthorsAuthorsBooksByIdBookResponse,
    AxiosError<DefaultError>,
    GetApiV1AuthorsAuthorsBooksByIdBookResponse,
    ReturnType<typeof getApiV1AuthorsAuthorsBooksByIdBookQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1AuthorsAuthorsBooksByIdBook({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthorsAuthorsBooksByIdBookQueryKey(options),
  });

export const deleteApiV1AuthorsByIdMutation = (
  options?: Partial<Options<DeleteApiV1AuthorsByIdData>>,
): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiV1AuthorsByIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiV1AuthorsByIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiV1AuthorsById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1AuthorsByIdQueryKey = (options: Options<GetApiV1AuthorsByIdData>) =>
  createQueryKey("getApiV1AuthorsById", options);

export const getApiV1AuthorsByIdOptions = (options: Options<GetApiV1AuthorsByIdData>) =>
  queryOptions<
    GetApiV1AuthorsByIdResponse,
    AxiosError<DefaultError>,
    GetApiV1AuthorsByIdResponse,
    ReturnType<typeof getApiV1AuthorsByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1AuthorsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthorsByIdQueryKey(options),
  });

export const putApiV1AuthorsByIdMutation = (
  options?: Partial<Options<PutApiV1AuthorsByIdData>>,
): UseMutationOptions<PutApiV1AuthorsByIdResponse, AxiosError<DefaultError>, Options<PutApiV1AuthorsByIdData>> => {
  const mutationOptions: UseMutationOptions<
    PutApiV1AuthorsByIdResponse,
    AxiosError<DefaultError>,
    Options<PutApiV1AuthorsByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiV1AuthorsById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1BooksQueryKey = (options?: Options<GetApiV1BooksData>) => createQueryKey("getApiV1Books", options);

export const getApiV1BooksOptions = (options?: Options<GetApiV1BooksData>) =>
  queryOptions<
    GetApiV1BooksResponse,
    AxiosError<DefaultError>,
    GetApiV1BooksResponse,
    ReturnType<typeof getApiV1BooksQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1Books({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1BooksQueryKey(options),
  });

export const postApiV1BooksMutation = (
  options?: Partial<Options<PostApiV1BooksData>>,
): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiV1BooksData>> => {
  const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiV1BooksData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1Books({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteApiV1BooksByIdMutation = (
  options?: Partial<Options<DeleteApiV1BooksByIdData>>,
): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiV1BooksByIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiV1BooksByIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiV1BooksById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1BooksByIdQueryKey = (options: Options<GetApiV1BooksByIdData>) =>
  createQueryKey("getApiV1BooksById", options);

export const getApiV1BooksByIdOptions = (options: Options<GetApiV1BooksByIdData>) =>
  queryOptions<
    GetApiV1BooksByIdResponse,
    AxiosError<DefaultError>,
    GetApiV1BooksByIdResponse,
    ReturnType<typeof getApiV1BooksByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1BooksById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1BooksByIdQueryKey(options),
  });

export const putApiV1BooksByIdMutation = (
  options?: Partial<Options<PutApiV1BooksByIdData>>,
): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PutApiV1BooksByIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PutApiV1BooksByIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiV1BooksById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1UsersQueryKey = (options?: Options<GetApiV1UsersData>) => createQueryKey("getApiV1Users", options);

export const getApiV1UsersOptions = (options?: Options<GetApiV1UsersData>) =>
  queryOptions<
    GetApiV1UsersResponse,
    AxiosError<DefaultError>,
    GetApiV1UsersResponse,
    ReturnType<typeof getApiV1UsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1Users({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1UsersQueryKey(options),
  });

export const postApiV1UsersMutation = (
  options?: Partial<Options<PostApiV1UsersData>>,
): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiV1UsersData>> => {
  const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostApiV1UsersData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1Users({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteApiV1UsersByIdMutation = (
  options?: Partial<Options<DeleteApiV1UsersByIdData>>,
): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiV1UsersByIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteApiV1UsersByIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiV1UsersById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1UsersByIdQueryKey = (options: Options<GetApiV1UsersByIdData>) =>
  createQueryKey("getApiV1UsersById", options);

export const getApiV1UsersByIdOptions = (options: Options<GetApiV1UsersByIdData>) =>
  queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof getApiV1UsersByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1UsersById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1UsersByIdQueryKey(options),
  });

export const putApiV1UsersByIdMutation = (
  options?: Partial<Options<PutApiV1UsersByIdData>>,
): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PutApiV1UsersByIdData>> => {
  const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PutApiV1UsersByIdData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiV1UsersById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
