// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeleteApiV1ActivitiesByIdData,
  DeleteApiV1ActivitiesByIdResponses,
  DeleteApiV1AuthorsByIdData,
  DeleteApiV1AuthorsByIdResponses,
  DeleteApiV1BooksByIdData,
  DeleteApiV1BooksByIdResponses,
  DeleteApiV1UsersByIdData,
  DeleteApiV1UsersByIdResponses,
  GetApiV1ActivitiesByIdData,
  GetApiV1ActivitiesByIdResponses,
  GetApiV1ActivitiesData,
  GetApiV1ActivitiesResponses,
  GetApiV1AuthorsAuthorsBooksByIdBookData,
  GetApiV1AuthorsAuthorsBooksByIdBookResponses,
  GetApiV1AuthorsByIdData,
  GetApiV1AuthorsByIdResponses,
  GetApiV1AuthorsData,
  GetApiV1AuthorsResponses,
  GetApiV1BooksByIdData,
  GetApiV1BooksByIdResponses,
  GetApiV1BooksData,
  GetApiV1BooksResponses,
  GetApiV1UsersByIdData,
  GetApiV1UsersByIdResponses,
  GetApiV1UsersData,
  GetApiV1UsersResponses,
  PostApiV1ActivitiesData,
  PostApiV1ActivitiesResponses,
  PostApiV1AuthorsData,
  PostApiV1AuthorsResponses,
  PostApiV1BooksData,
  PostApiV1BooksResponses,
  PostApiV1UsersData,
  PostApiV1UsersResponses,
  PutApiV1ActivitiesByIdData,
  PutApiV1ActivitiesByIdResponses,
  PutApiV1AuthorsByIdData,
  PutApiV1AuthorsByIdResponses,
  PutApiV1BooksByIdData,
  PutApiV1BooksByIdResponses,
  PutApiV1UsersByIdData,
  PutApiV1UsersByIdResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getApiV1Activities = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1ActivitiesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiV1ActivitiesResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Activities",
    ...options,
  });

export const postApiV1Activities = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1ActivitiesData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostApiV1ActivitiesResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Activities",
    ...options,
    headers: {
      "Content-Type": "application/json; v=1.0",
      ...options?.headers,
    },
  });

export const deleteApiV1ActivitiesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1ActivitiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteApiV1ActivitiesByIdResponses, unknown, ThrowOnError>({
    url: "/api/v1/Activities/{id}",
    ...options,
  });

export const getApiV1ActivitiesById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1ActivitiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiV1ActivitiesByIdResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Activities/{id}",
    ...options,
  });

export const putApiV1ActivitiesById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1ActivitiesByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutApiV1ActivitiesByIdResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Activities/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json; v=1.0",
      ...options.headers,
    },
  });

export const getApiV1Authors = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1AuthorsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiV1AuthorsResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Authors",
    ...options,
  });

export const postApiV1Authors = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1AuthorsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostApiV1AuthorsResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Authors",
    ...options,
    headers: {
      "Content-Type": "application/json; v=1.0",
      ...options?.headers,
    },
  });

export const getApiV1AuthorsAuthorsBooksByIdBook = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1AuthorsAuthorsBooksByIdBookData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiV1AuthorsAuthorsBooksByIdBookResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Authors/authors/books/{idBook}",
    ...options,
  });

export const deleteApiV1AuthorsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1AuthorsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteApiV1AuthorsByIdResponses, unknown, ThrowOnError>({
    url: "/api/v1/Authors/{id}",
    ...options,
  });

export const getApiV1AuthorsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1AuthorsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiV1AuthorsByIdResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Authors/{id}",
    ...options,
  });

export const putApiV1AuthorsById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1AuthorsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutApiV1AuthorsByIdResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Authors/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json; v=1.0",
      ...options.headers,
    },
  });

export const getApiV1Books = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1BooksData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiV1BooksResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Books",
    ...options,
  });

export const postApiV1Books = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1BooksData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostApiV1BooksResponses, unknown, ThrowOnError>({
    url: "/api/v1/Books",
    ...options,
    headers: {
      "Content-Type": "application/json; v=1.0",
      ...options?.headers,
    },
  });

export const deleteApiV1BooksById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1BooksByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteApiV1BooksByIdResponses, unknown, ThrowOnError>({
    url: "/api/v1/Books/{id}",
    ...options,
  });

export const getApiV1BooksById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1BooksByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiV1BooksByIdResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Books/{id}",
    ...options,
  });

export const putApiV1BooksById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1BooksByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutApiV1BooksByIdResponses, unknown, ThrowOnError>({
    url: "/api/v1/Books/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json; v=1.0",
      ...options.headers,
    },
  });

export const getApiV1Users = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1UsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiV1UsersResponses, unknown, ThrowOnError>({
    responseType: "json",
    url: "/api/v1/Users",
    ...options,
  });

export const postApiV1Users = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1UsersData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostApiV1UsersResponses, unknown, ThrowOnError>({
    url: "/api/v1/Users",
    ...options,
    headers: {
      "Content-Type": "application/json; v=1.0",
      ...options?.headers,
    },
  });

export const deleteApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1UsersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteApiV1UsersByIdResponses, unknown, ThrowOnError>({
    url: "/api/v1/Users/{id}",
    ...options,
  });

export const getApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1UsersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiV1UsersByIdResponses, unknown, ThrowOnError>({
    url: "/api/v1/Users/{id}",
    ...options,
  });

export const putApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1UsersByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutApiV1UsersByIdResponses, unknown, ThrowOnError>({
    url: "/api/v1/Users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json; v=1.0",
      ...options.headers,
    },
  });
