// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zActivity = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  title: z.string().nullish(),
  dueDate: z.iso.datetime().optional(),
  completed: z.boolean().optional(),
});

export const zAuthor = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  idBook: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  firstName: z.string().nullish(),
  lastName: z.string().nullish(),
});

export const zBook = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  title: z.string().nullish(),
  description: z.string().nullish(),
  pageCount: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  excerpt: z.string().nullish(),
  publishDate: z.iso.datetime().optional(),
});

export const zUser = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" })
    .optional(),
  userName: z.string().nullish(),
  password: z.string().nullish(),
});

/**
 * Success
 */
export const zGetApiV1ActivitiesResponse = z.array(zActivity);

export const zPostApiV1ActivitiesBody = zActivity;

/**
 * Success
 */
export const zPostApiV1ActivitiesResponse = zActivity;

export const zDeleteApiV1ActivitiesByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

export const zGetApiV1ActivitiesByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * Success
 */
export const zGetApiV1ActivitiesByIdResponse = zActivity;

export const zPutApiV1ActivitiesByIdBody = zActivity;

export const zPutApiV1ActivitiesByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * Success
 */
export const zPutApiV1ActivitiesByIdResponse = zActivity;

/**
 * Success
 */
export const zGetApiV1AuthorsResponse = z.array(zAuthor);

export const zPostApiV1AuthorsBody = zAuthor;

/**
 * Success
 */
export const zPostApiV1AuthorsResponse = zAuthor;

export const zGetApiV1AuthorsAuthorsBooksByIdBookPath = z.object({
  idBook: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * Success
 */
export const zGetApiV1AuthorsAuthorsBooksByIdBookResponse = z.array(zAuthor);

export const zDeleteApiV1AuthorsByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

export const zGetApiV1AuthorsByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * Success
 */
export const zGetApiV1AuthorsByIdResponse = zAuthor;

export const zPutApiV1AuthorsByIdBody = zAuthor;

export const zPutApiV1AuthorsByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * Success
 */
export const zPutApiV1AuthorsByIdResponse = zAuthor;

/**
 * Success
 */
export const zGetApiV1BooksResponse = z.array(zBook);

export const zPostApiV1BooksBody = zBook;

export const zDeleteApiV1BooksByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

export const zGetApiV1BooksByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * Success
 */
export const zGetApiV1BooksByIdResponse = zBook;

export const zPutApiV1BooksByIdBody = zBook;

export const zPutApiV1BooksByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

/**
 * Success
 */
export const zGetApiV1UsersResponse = z.array(zUser);

export const zPostApiV1UsersBody = zUser;

export const zDeleteApiV1UsersByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

export const zGetApiV1UsersByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});

export const zPutApiV1UsersByIdBody = zUser;

export const zPutApiV1UsersByIdPath = z.object({
  id: z
    .int()
    .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
    .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
});
